name: lbnl-resistive-casing

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - numpy
  - scipy
  - matplotlib
  - ipywidgets
  - mkl
  - geoana==0.0.5
  - pymatsolver==0.1.2
  - discretize==0.4.10
  - pip:
    - git+https://github.com/simpeg/simpeg.git@simulation
    - git+https://github.com/simpeg-research/casingSimulations.git@simulation
    
